// JSON support for code generated by `facet_generate` with its `JsonPlugin`.
//
// The generated types conform to `Codable` and are encoded with Foundation's
// `JSONEncoder` / `JSONDecoder`, in the shape `serde_json` gives the same
// Rust types. This file holds the little that the generated code shares:
// `Codable` for the runtime's `Int128` / `UInt128`, adapters for the values
// Swift cannot encode the way Rust does (`()`, `char`, `Uuid`), the key type
// for objects with computed keys, and the `jsonSerialize` / `jsonDeserialize`
// entry points.

import Foundation

/// Encodes `value` as JSON.
public func jsonSerialize<T: Encodable>(_ value: T) throws -> [UInt8] {
    return [UInt8](try JSONEncoder().encode(value))
}

/// Decodes a value of type `type` from JSON.
public func jsonDeserialize<T: Decodable>(_ type: T.Type, from input: [UInt8]) throws -> T {
    return try JSONDecoder().decode(type, from: Data(input))
}

/// A coding key spelled at run time: a map key, or an enum's tag or content
/// field.
public struct JsonKey: CodingKey {
    public var stringValue: String
    public var intValue: Int? { nil }

    public init(_ stringValue: String) {
        self.stringValue = stringValue
    }

    public init?(stringValue: String) {
        self.stringValue = stringValue
    }

    public init?(intValue: Int) {
        return nil
    }
}

/// Rust's `()`, which JSON writes as `null`.
public struct JsonUnit: Codable {
    public var value: Void { () }

    public init() {}

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        guard container.decodeNil() else {
            throw DecodingError.typeMismatch(
                JsonUnit.self,
                .init(codingPath: decoder.codingPath, debugDescription: "Expected null for ()")
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encodeNil()
    }
}

/// Rust's `char`, which JSON writes as a one-character string.
public struct JsonChar: Codable {
    public var value: Character

    public init(_ value: Character) {
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let string = try container.decode(String.self)
        guard string.count == 1, let value = string.first else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Expected a single character, found \"\(string)\""
            )
        }
        self.value = value
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(String(value))
    }
}

/// A `Uuid`, which JSON writes as a lowercase hyphenated string (Foundation's
/// own `UUID` coding writes it in uppercase).
public struct JsonUuid: Codable {
    public var value: UUID

    public init(_ value: UUID) {
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let string = try container.decode(String.self)
        guard let value = UUID(uuidString: string) else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Invalid UUID string: \(string)"
            )
        }
        self.value = value
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value.uuidString.lowercased())
    }
}

/// The object key JSON gives the map key `key`: a string as it is, and an
/// integer or a boolean as its literal — the keys `serde_json` accepts.
public func jsonMapKey<K: Encodable>(_ key: K) throws -> String {
    let data = try JSONEncoder().encode([key])
    let literal = String(decoding: data.dropFirst().dropLast(), as: UTF8.self)
    if literal.hasPrefix("\"") {
        return try JSONDecoder().decode([String].self, from: data)[0]
    }
    if isKeyLiteral(literal) {
        return literal
    }
    throw EncodingError.invalidValue(
        key,
        .init(codingPath: [], debugDescription: "A JSON object key must be a string, an integer or a boolean")
    )
}

/// The map key of type `type` that the JSON object key `string` spells.
public func jsonMapKey<K: Decodable>(_ string: String, as type: K.Type) throws -> K {
    let decoder = JSONDecoder()
    if let value = try? decoder.decode([K].self, from: JSONEncoder().encode([string])) {
        return value[0]
    }
    if isKeyLiteral(string), let value = try? decoder.decode([K].self, from: Data("[\(string)]".utf8)) {
        return value[0]
    }
    throw DecodingError.dataCorrupted(
        .init(codingPath: [], debugDescription: "Invalid key \"\(string)\" for \(K.self)")
    )
}

private func isKeyLiteral(_ literal: String) -> Bool {
    if literal == "true" || literal == "false" {
        return true
    }
    let digits = literal.hasPrefix("-") ? literal.dropFirst() : Substring(literal)
    return !digits.isEmpty && digits.allSatisfy { $0 >= "0" && $0 <= "9" }
}

// MARK: - 128-bit integers
//
// `serde_json` writes a 128-bit integer as a plain JSON number, which may not
// fit a `Double`. `JSONEncoder` / `JSONDecoder` write and read a `Decimal`
// digit for digit, and `Decimal(string:)` / `description` convert it to and
// from its digits exactly (a 128-bit integer has at most 39), so the values go
// through their decimal digits, computed with integer arithmetic on the two
// halves. Only public, cross-platform API is used: `Decimal`'s underscored
// members are public in Apple's Foundation alone.

extension UInt128: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let (negative, high, low) = try decodeInteger128(container)
        guard !negative || (high == 0 && low == 0) else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "UInt128 cannot be negative")
        }
        self.init(high: high, low: low)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(try decimal(negative: false, high: high, low: low, encoder: encoder))
    }
}

extension Int128: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let (negative, high, low) = try decodeInteger128(container)
        let limit: UInt64 = 1 << 63
        if negative {
            guard high < limit || (high == limit && low == 0) else {
                throw DecodingError.dataCorruptedError(in: container, debugDescription: "Int128 out of range")
            }
            let (h, l) = negate(high, low)
            self.init(high: Int64(bitPattern: h), low: l)
        } else {
            guard high < limit else {
                throw DecodingError.dataCorruptedError(in: container, debugDescription: "Int128 out of range")
            }
            self.init(high: Int64(bitPattern: high), low: low)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        if high < 0 {
            let (h, l) = negate(UInt64(bitPattern: high), low)
            try container.encode(try decimal(negative: true, high: h, low: l, encoder: encoder))
        } else {
            try container.encode(try decimal(negative: false, high: UInt64(high), low: low, encoder: encoder))
        }
    }
}

/// Two's complement negation of a 128-bit value.
private func negate(_ high: UInt64, _ low: UInt64) -> (UInt64, UInt64) {
    let (l, overflow) = (~low).addingReportingOverflow(1)
    return (~high &+ (overflow ? 1 : 0), l)
}

/// The integer `(-1)^negative * (high << 64 | low)` as a `Decimal`.
private func decimal(negative: Bool, high: UInt64, low: UInt64, encoder: Encoder) throws -> Decimal {
    var (high, low) = (high, low)
    var digits: [Character] = []
    repeat {
        // Divide the 128-bit value by 10, keeping the remainder as a digit.
        let (qh, rh) = high.quotientAndRemainder(dividingBy: 10)
        let (ql, r) = UInt64(10).dividingFullWidth((rh, low))
        digits.append(Character(String(r)))
        (high, low) = (qh, ql)
    } while high != 0 || low != 0
    let text = (negative ? "-" : "") + String(digits.reversed())
    guard let value = Decimal(string: text) else {
        throw EncodingError.invalidValue(
            text,
            .init(codingPath: encoder.codingPath, debugDescription: "Cannot write \(text) as a JSON number")
        )
    }
    return value
}

/// Reads an integer JSON number of up to 128 bits of magnitude, as its sign
/// and magnitude.
private func decodeInteger128(_ container: SingleValueDecodingContainer) throws -> (Bool, UInt64, UInt64) {
    let value = try container.decode(Decimal.self)
    // `description` spells out every digit, with no exponent: 1e3 is "1000",
    // and 12.0 is "12".
    let text = value.description
    let negative = text.hasPrefix("-")
    let digits = negative ? text.dropFirst() : Substring(text)
    guard !value.isNaN, !digits.isEmpty, digits.allSatisfy({ $0 >= "0" && $0 <= "9" }) else {
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected an integer, found \(text)")
    }
    var (high, low): (UInt64, UInt64) = (0, 0)
    for digit in digits.utf8 {
        // Multiply the 128-bit value by 10 and add the digit.
        let (carry, l) = low.multipliedFullWidth(by: 10)
        let (h, overflow) = high.multipliedReportingOverflow(by: 10)
        let (withCarry, carried) = h.addingReportingOverflow(carry)
        let (sum, added) = l.addingReportingOverflow(UInt64(digit - UInt8(ascii: "0")))
        let (withAdd, addCarried) = withCarry.addingReportingOverflow(added ? 1 : 0)
        guard !overflow, !carried, !addCarried else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Integer out of range: \(text)")
        }
        (high, low) = (withAdd, sum)
    }
    return (negative, high, low)
}
