// JSON support for code generated by `facet_generate` with its `JsonPlugin`.
//
// Each generated type converts itself to and from a plain JSON value in the
// shape `serde_json` gives the same Rust type; `JSON.stringify` and
// `JSON.parse` do the text. This file holds the little that the generated
// code shares: the readers that check a JSON value's shape, and the exact
// reading and writing of 64- and 128-bit integers, which a JavaScript number
// cannot hold.
//
// An integer beyond 2^53 is read from its source text (`JSON.parse`'s
// reviver `context.source`) and written with `JSON.rawJSON`, both from the
// JSON.parse source text access proposal (Node 21+, Deno 1.37+, Chrome 114+,
// Safari 18.4+, Firefox 135+). Without them, such an integer throws.

/** A value `JSON.stringify` writes: what a generated `toJson` returns. */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

type RawJson = { readonly rawJSON: string };

const platform = JSON as unknown as {
  rawJSON?: (text: string) => RawJson;
  isRawJSON?: (value: unknown) => value is RawJson;
};

const REQUIREMENT =
  "JSON.parse source text access (JSON.rawJSON and the reviver's context.source; Node 21+)";

/** The JSON text for `value`. */
export function stringify(value: JsonValue): string {
  return JSON.stringify(value);
}

/**
 * The JSON value `text` holds, with each integer beyond 2^53 read exactly as
 * a `bigint`.
 */
export function parse(text: string): unknown {
  return JSON.parse(
    text,
    function (_key: string, value: unknown, context?: { source?: string }) {
      if (
        typeof value === "number" &&
        !Number.isSafeInteger(value) &&
        context?.source !== undefined &&
        /^-?\d+$/.test(context.source)
      ) {
        return BigInt(context.source);
      }
      return value;
    },
  );
}

function fail(message: string): Error {
  return new Error(message);
}

function describe(json: unknown): string {
  if (json === undefined) return "nothing";
  let text: string;
  try {
    text = typeof json === "bigint" ? json.toString() : (JSON.stringify(json) ?? String(json));
  } catch {
    text = String(json);
  }
  return text.length > 60 ? `${text.slice(0, 60)}…` : text;
}

function expected(what: string, json: unknown): Error {
  return fail(`expected ${what}, found ${describe(json)}`);
}

function raw(json: unknown): string | undefined {
  return platform.isRawJSON?.(json) ? json.rawJSON : undefined;
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

export function readUnit(json: unknown): null {
  if (json !== null) throw expected("null", json);
  return null;
}

export function readBool(json: unknown): boolean {
  if (typeof json !== "boolean") throw expected("a boolean", json);
  return json;
}

function readInteger(json: unknown, what: string, min: number, max: number): number {
  if (typeof json !== "number" || !Number.isInteger(json) || json < min || json > max) {
    throw expected(what, json);
  }
  return json;
}

export const readI8 = (json: unknown) => readInteger(json, "an i8", -0x80, 0x7f);
export const readI16 = (json: unknown) => readInteger(json, "an i16", -0x8000, 0x7fff);
export const readI32 = (json: unknown) => readInteger(json, "an i32", -0x80000000, 0x7fffffff);
export const readU8 = (json: unknown) => readInteger(json, "a u8", 0, 0xff);
export const readU16 = (json: unknown) => readInteger(json, "a u16", 0, 0xffff);
export const readU32 = (json: unknown) => readInteger(json, "a u32", 0, 0xffffffff);

function readBigInt(json: unknown, what: string, bits: number, signed: boolean): bigint {
  let value: bigint | undefined;
  const text = raw(json);
  if (typeof json === "bigint") {
    value = json;
  } else if (text !== undefined && /^-?\d+$/.test(text)) {
    value = BigInt(text);
  } else if (typeof json === "number" && Number.isInteger(json)) {
    if (!Number.isSafeInteger(json)) {
      throw fail(`${what} beyond 2^53 has lost precision: reading it exactly needs ${REQUIREMENT}`);
    }
    value = BigInt(json);
  }
  const min = signed ? -(1n << BigInt(bits - 1)) : 0n;
  const max = (signed ? 1n << BigInt(bits - 1) : 1n << BigInt(bits)) - 1n;
  if (value === undefined || value < min || value > max) throw expected(what, json);
  return value;
}

export const readI64 = (json: unknown) => readBigInt(json, "an i64", 64, true);
export const readI128 = (json: unknown) => readBigInt(json, "an i128", 128, true);
export const readU64 = (json: unknown) => readBigInt(json, "a u64", 64, false);
export const readU128 = (json: unknown) => readBigInt(json, "a u128", 128, false);

function readFloat(json: unknown, what: string): number {
  const text = raw(json);
  if (typeof json === "number") return json;
  if (typeof json === "bigint") return Number(json);
  if (text !== undefined) return Number(text);
  throw expected(what, json);
}

export const readF32 = (json: unknown) => readFloat(json, "an f32");
export const readF64 = (json: unknown) => readFloat(json, "an f64");

export function readStr(json: unknown): string {
  if (typeof json !== "string") throw expected("a string", json);
  return json;
}

/** A string of exactly one Unicode scalar value. */
export function readChar(json: unknown): string {
  if (typeof json !== "string" || [...json].length !== 1) throw expected("a char", json);
  return json;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** A hyphenated UUID, in lower case. */
export function readUuid(json: unknown): string {
  if (typeof json !== "string" || !UUID.test(json)) throw expected("a UUID", json);
  return json.toLowerCase();
}

export function readBytes(json: unknown): Uint8Array {
  return new Uint8Array(readSeq(json, readU8));
}

/** `null` for `null` or a missing field, and the value otherwise. */
export function readOption<T>(json: unknown, read: (json: unknown) => T): T | null {
  return json === null || json === undefined ? null : read(json);
}

export function readSeq<T>(json: unknown, read: (json: unknown) => T, length?: number): T[] {
  if (!Array.isArray(json)) throw expected("an array", json);
  if (length !== undefined && json.length !== length) {
    throw expected(`an array of ${length}`, json);
  }
  return json.map((item) => read(item));
}

/** An array holding exactly one element for each of `readers`. */
export function readTuple<T extends unknown[]>(
  json: unknown,
  readers: { [K in keyof T]: (json: unknown) => T[K] },
): T {
  const items = readSeq(json, (item) => item, readers.length);
  return readers.map((read, i) => read(items[i])) as T;
}

export function readObject(json: unknown, what: string): Record<string, unknown> {
  if (typeof json !== "object" || json === null || Array.isArray(json) || raw(json) !== undefined) {
    throw expected(`an object for ${what}`, json);
  }
  return json as Record<string, unknown>;
}

/** The field `key` of `object`, or `undefined` when it has none. */
export function field(object: Record<string, unknown>, key: string): unknown {
  return Object.prototype.hasOwnProperty.call(object, key) ? object[key] : undefined;
}

/** `null` or an object: Rust writes a unit struct as `null`, and `struct S {}` as `{}`. */
export function readUnitStruct(json: unknown, what: string): void {
  if (json !== null) readObject(json, what);
}

export function readMap<K, V>(
  json: unknown,
  readKey: (key: string) => K,
  readValue: (json: unknown) => V,
): Map<K, V> {
  const object = readObject(json, "a map");
  const map = new Map<K, V>();
  for (const key of Object.keys(object)) {
    map.set(readKey(key), readValue(object[key]));
  }
  return map;
}

/** The boolean or integer that the map key `key` spells. */
export function keyLiteral(key: string): unknown {
  if (key === "true") return true;
  if (key === "false") return false;
  if (/^-?\d+$/.test(key)) {
    const value = Number(key);
    return Number.isSafeInteger(value) ? value : BigInt(key);
  }
  throw expected("a boolean or an integer key", key);
}

/** The map key `key` as `read` reads it: as a string, or as the literal it spells. */
export function readKey<T>(key: string, read: (json: unknown) => T): T {
  try {
    return read(key);
  } catch (error) {
    if (key !== "true" && key !== "false" && !/^-?\d+$/.test(key)) throw error;
    return read(keyLiteral(key));
  }
}

/**
 * The variant and content of an externally tagged enum: `"Variant"` for a
 * unit variant, or `{"Variant": content}`.
 */
export function readExternal(
  json: unknown,
  what: string,
  units: readonly string[],
): [string, unknown] {
  if (typeof json === "string") {
    if (!units.includes(json)) throw unknownVariant(what, json);
    return [json, null];
  }
  const object = readObject(json, what);
  const keys = Object.keys(object);
  if (keys.length !== 1) throw expected(`one variant of ${what}`, json);
  const variant = keys[0];
  if (units.includes(variant)) readUnit(object[variant]);
  return [variant, object[variant]];
}

/** The variant of an internally tagged enum, and the object holding its fields. */
export function readInternal(
  json: unknown,
  tag: string,
  what: string,
): [string, Record<string, unknown>] {
  const object = readObject(json, what);
  return [readStr(field(object, tag)), object];
}

/** The variant and content of an adjacently tagged enum. */
export function readAdjacent(
  json: unknown,
  tag: string,
  content: string,
  what: string,
  units: readonly string[],
): [string, unknown] {
  const object = readObject(json, what);
  const variant = readStr(field(object, tag));
  const value = field(object, content);
  if (units.includes(variant)) readOption(value, readUnit);
  return [variant, value];
}

/** A copy of `object` without its field `tag`. */
export function untag(object: Record<string, unknown>, tag: string): Record<string, unknown> {
  const { [tag]: _, ...rest } = object;
  return rest;
}

export function unknownVariant(what: string, variant: unknown): Error {
  return fail(`unknown variant ${describe(variant)} of ${what}`);
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

function rawJson(text: string, what: string): JsonValue {
  if (platform.rawJSON === undefined) {
    throw fail(`writing ${what} exactly needs ${REQUIREMENT}`);
  }
  return platform.rawJSON(text) as unknown as JsonValue;
}

/** A 64- or 128-bit integer: a plain number up to 2^53, and exact beyond. */
export function writeBigInt(value: bigint): JsonValue {
  const number = Number(value);
  return Number.isSafeInteger(number) ? number : rawJson(value.toString(), `${value}`);
}

/**
 * A float as Rust writes it: always with a fraction or an exponent (`3.0`),
 * and `null` when not finite.
 */
export function writeFloat(value: number): JsonValue {
  if (!Number.isFinite(value)) return null;
  if (!Number.isInteger(value) || platform.rawJSON === undefined) return value;
  const text = Object.is(value, -0) ? "-0" : String(value);
  return platform.rawJSON(/e/.test(text) ? text : `${text}.0`) as unknown as JsonValue;
}

export function writeBytes(value: Uint8Array): JsonValue {
  return Array.from(value);
}

export function writeMap<K, V>(
  value: Map<K, V>,
  writeKey: (key: K) => string,
  writeValue: (value: V) => JsonValue,
): JsonValue {
  const object: { [key: string]: JsonValue } = Object.create(null);
  for (const [k, v] of value) {
    object[writeKey(k)] = writeValue(v);
  }
  return object;
}

/** The map key for a value whose JSON is a string, a boolean or an integer. */
export function writeKey(json: JsonValue): string {
  const text = raw(json);
  if (typeof json === "string") return json;
  if (typeof json === "boolean" || (typeof json === "number" && Number.isInteger(json))) {
    return String(json);
  }
  if (text !== undefined && /^-?\d+$/.test(text)) return text;
  throw expected("a string, boolean or integer map key", json);
}

/**
 * `{"tag": variant, ...content}`: an internally tagged newtype variant, whose
 * content must be an object, or `null` for a unit struct.
 */
export function writeTagged(tag: string, variant: string, content: JsonValue): JsonValue {
  if (content === null) return { [tag]: variant };
  if (typeof content !== "object" || Array.isArray(content) || raw(content) !== undefined) {
    throw expected(`an object to tag with ${tag}`, content);
  }
  return { [tag]: variant, ...content };
}
