//! The types that `import Foundation` brings into scope.

/// The public top-level types that a module importing `Foundation` finds
/// (structs, enums, classes, protocols and typealiases, whether declared in
/// Swift or imported from C or Objective-C), each with the module that
/// declares it, less those that start with `_`, those no namespace becomes
/// (`URL`, `NSObject`) and those in scope without `Foundation`. Sorted by
/// name.
///
/// Swift looks a qualifier up as a type before it looks for a module, so in a
/// module that imports `Foundation` itself, a module named like one of these
/// cannot be qualified: `Data.Foo` looks for `Foo` in `Foundation.Data`. The
/// import is not transitive: a module that imports only `Serde`, or another
/// module, which imports `Foundation` does not find these.
//
// Generated with Apple Swift 6.4 (swiftlang-6.4.0.34.1), macOS 27.0 SDK. The
// candidates are the names of the symbols of kind `swift.{struct,enum,class,
// protocol,actor,typealias}` with a single path component in the graphs that
// `swift-symbolgraph-extract -minimum-access-level public -target
// arm64-apple-macosx27.0` writes for `Foundation` and for every module that a
// file holding only `import Foundation` loads (the `.pcm`s in a fresh
// `-module-cache-path`, and its `-emit-loaded-module-trace`), keeping each
// that does not start with `_` and for which
// `name.to_snake_case().to_upper_camel_case() == name` (heck 0.5). Of those,
// each is kept for which `swiftc -typecheck` of `import Foundation` and
// `public typealias P = Name.Missing` fails with "'Missing' is not a member
// type of ... 'Module.Name'" (the module is the one it names), and for which
// the same without the import fails with "cannot find type". Sorted
// bytewise.
pub(crate) const FOUNDATION_TYPES: &[(&str, &str)] = &[
    ("AffineTransform", "Foundation"),
    ("AlignmentOptions", "Foundation"),
    ("AppleEvent", "CoreServices"),
    ("AppleEventPtr", "CoreServices"),
    ("AsyncCharacterSequence", "Foundation"),
    ("AsyncLineSequence", "Foundation"),
    ("AsyncUnicodeScalarSequence", "Foundation"),
    ("AttributeContainer", "Foundation"),
    ("AttributeDynamicLookup", "Foundation"),
    ("AttributeScope", "Foundation"),
    ("AttributeScopeCodableConfiguration", "Foundation"),
    ("AttributeScopes", "Foundation"),
    ("AttributedString", "Foundation"),
    ("AttributedStringAttributeMutation", "Foundation"),
    ("AttributedStringKey", "Foundation"),
    ("AttributedStringProtocol", "Foundation"),
    ("AttributedSubstring", "Foundation"),
    ("AuthorizationAsyncCallback", "Security"),
    ("AuthorizationEnvironment", "Security"),
    ("AuthorizationExternalForm", "Security"),
    ("AuthorizationFlags", "Security"),
    ("AuthorizationItem", "Security"),
    ("AuthorizationItemSet", "Security"),
    ("AuthorizationRef", "Security"),
    ("AuthorizationRights", "Security"),
    ("AuthorizationString", "Security"),
    ("BTreeKey", "Darwin"),
    ("BTreeKeyLimits", "Darwin"),
    ("BlockOperation", "Foundation"),
    ("Bundle", "Foundation"),
    ("ByteCountFormatStyle", "Foundation"),
    ("ByteCountFormatter", "Foundation"),
    ("Calendar", "Foundation"),
    ("Category", "ObjectiveC"),
    ("CharacterSet", "Foundation"),
    ("CocoaError", "Foundation"),
    ("CodableAttributedStringKey", "Foundation"),
    ("CodableConfiguration", "Foundation"),
    ("CodableWithConfiguration", "Foundation"),
    ("CollatorRef", "CoreServices"),
    ("ComparableComparator", "Foundation"),
    ("Comparator", "Foundation"),
    ("ComparisonResult", "Foundation"),
    ("ContiguousBytes", "Foundation"),
    ("CurrencyFormatStyleConfiguration", "Foundation"),
    ("CustomLocalizedStringResourceConvertible", "Foundation"),
    ("DarwinBoolean", "Darwin"),
    ("Data", "Foundation"),
    ("DataProtocol", "Foundation"),
    ("Date", "Foundation"),
    ("DateComponents", "Foundation"),
    ("DateComponentsFormatter", "Foundation"),
    ("DateFormatter", "Foundation"),
    ("DateInterval", "Foundation"),
    ("DateIntervalFormatter", "Foundation"),
    ("Decimal", "Foundation"),
    ("DecodableAttributedStringKey", "Foundation"),
    ("DecodableWithConfiguration", "Foundation"),
    ("DecodingConfigurationProviding", "Foundation"),
    ("DescType", "CoreServices"),
    ("DescriptiveNumberFormatConfiguration", "Foundation"),
    ("Dimension", "Foundation"),
    ("DiscontiguousAttributedSubstring", "Foundation"),
    ("DiscreteFormatStyle", "Foundation"),
    ("DispatchConcurrentQueue", "Dispatch"),
    ("DispatchData", "Dispatch"),
    ("DispatchDataIterator", "Dispatch"),
    ("DispatchGroup", "Dispatch"),
    ("DispatchObject", "Dispatch"),
    ("DispatchPredicate", "Dispatch"),
    ("DispatchQoS", "Dispatch"),
    ("DispatchQueue", "Dispatch"),
    ("DispatchSemaphore", "Dispatch"),
    ("DispatchSerialQueue", "Dispatch"),
    ("DispatchSource", "Dispatch"),
    ("DispatchSourceFileSystemObject", "Dispatch"),
    ("DispatchSourceMachReceive", "Dispatch"),
    ("DispatchSourceMachSend", "Dispatch"),
    ("DispatchSourceMemoryPressure", "Dispatch"),
    ("DispatchSourceProcess", "Dispatch"),
    ("DispatchSourceProtocol", "Dispatch"),
    ("DispatchSourceRead", "Dispatch"),
    ("DispatchSourceSignal", "Dispatch"),
    ("DispatchSourceTimer", "Dispatch"),
    ("DispatchSourceUserDataAdd", "Dispatch"),
    ("DispatchSourceUserDataOr", "Dispatch"),
    ("DispatchSourceUserDataReplace", "Dispatch"),
    ("DispatchSourceWrite", "Dispatch"),
    ("DispatchSpecificKey", "Dispatch"),
    ("DispatchTime", "Dispatch"),
    ("DispatchTimeInterval", "Dispatch"),
    ("DispatchTimeoutResult", "Dispatch"),
    ("DispatchWallTime", "Dispatch"),
    ("DispatchWorkItem", "Dispatch"),
    ("DispatchWorkItemFlags", "Dispatch"),
    ("DispatchWorkloop", "Dispatch"),
    ("DistributedNotificationCenter", "Foundation"),
    ("EncodableAttributedStringKey", "Foundation"),
    ("EncodableWithConfiguration", "Foundation"),
    ("EncodingConfigurationProviding", "Foundation"),
    ("EnergyFormatter", "Foundation"),
    ("ErrorPointer", "Foundation"),
    ("ErrorUserInfoKey", "Foundation"),
    ("Expression", "Foundation"),
    ("FileAttributeKey", "Foundation"),
    ("FileAttributeType", "Foundation"),
    ("FileHandle", "Foundation"),
    ("FileManager", "Foundation"),
    ("FileManagerDelegate", "Foundation"),
    ("FileProtectionType", "Foundation"),
    ("FileWrapper", "Foundation"),
    ("FloatingPointFormatStyle", "Foundation"),
    ("FloatingPointParseStrategy", "Foundation"),
    ("FndrDirInfo", "Darwin"),
    ("FndrExtendedDirInfo", "Darwin"),
    ("FndrExtendedFileInfo", "Darwin"),
    ("FndrFileInfo", "Darwin"),
    ("FndrOpaqueInfo", "Darwin"),
    ("FormatStyle", "Foundation"),
    ("FormatStyleCapitalizationContext", "Foundation"),
    ("Formatter", "Foundation"),
    ("FourCharCode", "Darwin"),
    ("Host", "Foundation"),
    ("IconRef", "CoreServices"),
    ("IconServicesUsageFlags", "CoreServices"),
    ("IndexPath", "Foundation"),
    ("IndexSet", "Foundation"),
    ("InflectionConcept", "Foundation"),
    ("InflectionRule", "Foundation"),
    ("InlinePresentationIntent", "Foundation"),
    ("InputStream", "Foundation"),
    ("IntegerFormatStyle", "Foundation"),
    ("IntegerParseStrategy", "Foundation"),
    ("IntlText", "CoreServices"),
    ("Ivar", "ObjectiveC"),
    ("JournalInfoBlock", "Darwin"),
    ("KeyPathComparator", "Foundation"),
    ("LengthFormatter", "Foundation"),
    ("ListFormatStyle", "Foundation"),
    ("ListFormatter", "Foundation"),
    ("Locale", "Foundation"),
    ("LocalizedError", "Foundation"),
    ("LocalizedStringResource", "Foundation"),
    ("MachError", "Foundation"),
    ("MachErrorCode", "Darwin"),
    ("MarkdownDecodableAttributedStringKey", "Foundation"),
    ("MassFormatter", "Foundation"),
    ("Measurement", "Foundation"),
    ("MeasurementFormatUnitUsage", "Foundation"),
    ("MeasurementFormatter", "Foundation"),
    ("MessagePort", "Foundation"),
    ("Method", "ObjectiveC"),
    ("Morphology", "Foundation"),
    ("MutableDataProtocol", "Foundation"),
    ("NetService", "Foundation"),
    ("NetServiceBrowser", "Foundation"),
    ("NetServiceBrowserDelegate", "Foundation"),
    ("NetServiceDelegate", "Foundation"),
    ("Notification", "Foundation"),
    ("NotificationCenter", "Foundation"),
    ("NotificationQueue", "Foundation"),
    ("NumberFormatStyleConfiguration", "Foundation"),
    ("NumberFormatter", "Foundation"),
    ("ObjCBool", "ObjectiveC"),
    ("ObjCClassList", "ObjectiveC"),
    ("ObjCEnumerationImage", "ObjectiveC"),
    ("ObjectiveCConvertibleAttributedStringKey", "Foundation"),
    ("Observable", "Observation"),
    ("ObservableObject", "Foundation"),
    ("ObservationRegistrar", "Observation"),
    ("ObservationTracking", "Observation"),
    ("Observations", "Observation"),
    ("OffsetArray", "CoreServices"),
    ("OffsetArrayHandle", "CoreServices"),
    ("OffsetArrayPtr", "CoreServices"),
    ("OperatingSystemVersion", "Foundation"),
    ("Operation", "Foundation"),
    ("OperationQueue", "Foundation"),
    ("OptionBits", "Darwin"),
    ("OutputStream", "Foundation"),
    ("Parallelizable", "os_workgroup"),
    ("ParseStrategy", "Foundation"),
    ("ParseableFormatStyle", "Foundation"),
    ("PersonNameComponents", "Foundation"),
    ("PersonNameComponentsFormatter", "Foundation"),
    ("Pipe", "Foundation"),
    ("Port", "Foundation"),
    ("PortDelegate", "Foundation"),
    ("PortMessage", "Foundation"),
    ("Predicate", "Foundation"),
    ("PredicateBindings", "Foundation"),
    ("PredicateCodableConfiguration", "Foundation"),
    ("PredicateCodableKeyPathProviding", "Foundation"),
    ("PredicateError", "Foundation"),
    ("PredicateExpression", "Foundation"),
    ("PredicateExpressions", "Foundation"),
    ("PresentationIntent", "Foundation"),
    ("Process", "Foundation"),
    ("ProcessInfo", "Foundation"),
    ("ProcessSerialNumber", "Darwin"),
    ("Progress", "Foundation"),
    ("ProgressKind", "Foundation"),
    ("ProgressManager", "Foundation"),
    ("ProgressReporter", "Foundation"),
    ("ProgressReporting", "Foundation"),
    ("ProgressUserInfoKey", "Foundation"),
    ("PropertyListDecoder", "Foundation"),
    ("PropertyListEncoder", "Foundation"),
    ("PropertyListSerialization", "Foundation"),
    ("Protocol", "ObjectiveC"),
    ("Published", "Foundation"),
    ("QualityOfService", "Foundation"),
    ("RecoverableError", "Foundation"),
    ("ReferenceConvertible", "Foundation"),
    ("RelativeDateTimeFormatter", "Foundation"),
    ("Repeatable", "os_workgroup"),
    ("RunLoop", "Foundation"),
    ("Scanner", "Foundation"),
    ("ScopedAttributeContainer", "Foundation"),
    ("SecAccess", "Security"),
    ("SecAccessControl", "Security"),
    ("SecAccessControlCreateFlags", "Security"),
    ("SecAccessOwnerType", "Security"),
    ("SecAsn1AlgId", "Security"),
    ("SecAsn1Item", "Security"),
    ("SecAsn1Oid", "Security"),
    ("SecAsn1PubKeyInfo", "Security"),
    ("SecAsn1Template", "Security"),
    ("SecAsn1TemplateChooser", "Security"),
    ("SecAsn1TemplateChooserPtr", "Security"),
    ("SecAuthenticationType", "Security"),
    ("SecCertificate", "Security"),
    ("SecCode", "Security"),
    ("SecCodeSignatureFlags", "Security"),
    ("SecCodeStatus", "Security"),
    ("SecCredentialType", "Security"),
    ("SecExternalFormat", "Security"),
    ("SecExternalItemType", "Security"),
    ("SecGroupTransform", "Security"),
    ("SecGuestRef", "Security"),
    ("SecIdentity", "Security"),
    ("SecIdentitySearch", "Security"),
    ("SecItemAttr", "Security"),
    ("SecItemClass", "Security"),
    ("SecItemImportExportFlags", "Security"),
    ("SecItemImportExportKeyParameters", "Security"),
    ("SecKey", "Security"),
    ("SecKeyAlgorithm", "Security"),
    ("SecKeyGeneratePairBlock", "Security"),
    ("SecKeyImportExportFlags", "Security"),
    ("SecKeyImportExportParameters", "Security"),
    ("SecKeyKeyExchangeParameter", "Security"),
    ("SecKeyOperationType", "Security"),
    ("SecKeySizes", "Security"),
    ("SecKeyUsage", "Security"),
    ("SecKeychain", "Security"),
    ("SecKeychainAttrType", "Security"),
    ("SecKeychainAttribute", "Security"),
    ("SecKeychainAttributeInfo", "Security"),
    ("SecKeychainAttributeList", "Security"),
    ("SecKeychainAttributePtr", "Security"),
    ("SecKeychainCallback", "Security"),
    ("SecKeychainCallbackInfo", "Security"),
    ("SecKeychainEvent", "Security"),
    ("SecKeychainEventMask", "Security"),
    ("SecKeychainItem", "Security"),
    ("SecKeychainPromptSelector", "Security"),
    ("SecKeychainSearch", "Security"),
    ("SecKeychainSettings", "Security"),
    ("SecKeychainStatus", "Security"),
    ("SecMessageBlock", "Security"),
    ("SecPadding", "Security"),
    ("SecPassword", "Security"),
    ("SecPolicy", "Security"),
    ("SecPolicySearch", "Security"),
    ("SecPreferencesDomain", "Security"),
    ("SecProtocolType", "Security"),
    ("SecPublicKeyHash", "Security"),
    ("SecRandomRef", "Security"),
    ("SecRequirement", "Security"),
    ("SecRequirementType", "Security"),
    ("SecStaticCode", "Security"),
    ("SecTask", "Security"),
    ("SecTransform", "Security"),
    ("SecTransformActionBlock", "Security"),
    ("SecTransformAttribute", "Security"),
    ("SecTransformAttributeActionBlock", "Security"),
    ("SecTransformDataBlock", "Security"),
    ("SecTransformImplementationRef", "Security"),
    ("SecTransformInstanceBlock", "Security"),
    ("SecTransformMetaAttributeType", "Security"),
    ("SecTransformStringOrAttribute", "Security"),
    ("SecTrust", "Security"),
    ("SecTrustCallback", "Security"),
    ("SecTrustOptionFlags", "Security"),
    ("SecTrustResultType", "Security"),
    ("SecTrustSettingsDomain", "Security"),
    ("SecTrustSettingsKeyUsage", "Security"),
    ("SecTrustSettingsResult", "Security"),
    ("SecTrustWithErrorCallback", "Security"),
    ("SecTrustedApplication", "Security"),
    ("SecuritySessionId", "Security"),
    ("Selector", "ObjectiveC"),
    ("Semaphore", "Darwin"),
    ("SessionAttributeBits", "Security"),
    ("SessionCreationFlags", "Security"),
    ("SocketNativeHandle", "Foundation"),
    ("SocketPort", "Foundation"),
    ("SortComparator", "Foundation"),
    ("SortDescriptor", "Foundation"),
    ("SortOrder", "Foundation"),
    ("StandardPredicateExpression", "Foundation"),
    ("Stream", "Foundation"),
    ("StreamDelegate", "Foundation"),
    ("StreamNetworkServiceTypeValue", "Foundation"),
    ("StreamSocketSecurityLevel", "Foundation"),
    ("StringEncodingDetectionOptionsKey", "Foundation"),
    ("StringStyle", "Foundation"),
    ("StringTransform", "Foundation"),
    ("Subprogress", "Foundation"),
    ("TScriptingSizeResource", "CoreServices"),
    ("TermOfAddress", "Foundation"),
    ("TextBreakLocatorRef", "CoreServices"),
    ("TextRange", "CoreServices"),
    ("TextRangeArray", "CoreServices"),
    ("TextRangeArrayHandle", "CoreServices"),
    ("TextRangeArrayPtr", "CoreServices"),
    ("TextRangeHandle", "CoreServices"),
    ("TextRangePtr", "CoreServices"),
    ("Thread", "Foundation"),
    ("TimeInterval", "Foundation"),
    ("TimeZone", "Foundation"),
    ("Timer", "Foundation"),
    ("UndoManager", "Foundation"),
    ("UniChar", "Darwin"),
    ("Unit", "Foundation"),
    ("UnitAcceleration", "Foundation"),
    ("UnitAngle", "Foundation"),
    ("UnitArea", "Foundation"),
    ("UnitConcentrationMass", "Foundation"),
    ("UnitConverter", "Foundation"),
    ("UnitConverterLinear", "Foundation"),
    ("UnitDispersion", "Foundation"),
    ("UnitDuration", "Foundation"),
    ("UnitElectricCharge", "Foundation"),
    ("UnitElectricCurrent", "Foundation"),
    ("UnitElectricPotentialDifference", "Foundation"),
    ("UnitElectricResistance", "Foundation"),
    ("UnitEnergy", "Foundation"),
    ("UnitFrequency", "Foundation"),
    ("UnitFuelEfficiency", "Foundation"),
    ("UnitIlluminance", "Foundation"),
    ("UnitInformationStorage", "Foundation"),
    ("UnitLength", "Foundation"),
    ("UnitMass", "Foundation"),
    ("UnitPower", "Foundation"),
    ("UnitPressure", "Foundation"),
    ("UnitSpeed", "Foundation"),
    ("UnitTemperature", "Foundation"),
    ("UnitVolume", "Foundation"),
    ("UserDefaults", "Foundation"),
    ("ValueTransformer", "Foundation"),
    ("WorkGroup", "os_workgroup"),
    ("WorkGroupInterval", "os_workgroup"),
    ("WorkGroupParallel", "os_workgroup"),
    ("WritingCode", "CoreServices"),
];

#[cfg(test)]
mod tests {
    use heck::{ToSnakeCase as _, ToUpperCamelCase as _};

    use super::FOUNDATION_TYPES;

    #[test]
    fn is_sorted_for_binary_search() {
        assert!(
            FOUNDATION_TYPES.windows(2).all(|w| w[0].0 < w[1].0),
            "FOUNDATION_TYPES must be sorted by name"
        );
    }

    #[test]
    fn holds_only_names_a_namespace_becomes() {
        for (name, _) in FOUNDATION_TYPES {
            assert!(!name.starts_with('_'), "{name}");
            assert_eq!(name.to_snake_case().to_upper_camel_case(), *name);
        }
    }
}
