// JSON support for code generated by `facet_generate` with its `JsonPlugin`.
//
// Every generated type names a generated `JsonConverter`, which writes it in
// the shape `serde_json` gives the same Rust type. Those converters are built
// from the ones below: a converter for each Rust format, composed as the
// format is (`FacetJson.List(FacetJson.Option(FacetJson.U32))`), and helpers
// for reading and writing objects, arrays and enum variants.

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace Facet.Runtime.Json;

/// <summary>
/// Converters for the Rust formats, and the helpers the generated converters
/// read and write with.
/// </summary>
public static partial class FacetJson
{
    public static readonly JsonConverter<Facet.Runtime.Serde.Unit> Unit = new UnitConverter();
    public static readonly JsonConverter<bool> Bool = new BoolConverter();
    public static JsonConverter<sbyte> I8 => JsonMetadataServices.SByteConverter;
    public static JsonConverter<short> I16 => JsonMetadataServices.Int16Converter;
    public static JsonConverter<int> I32 => JsonMetadataServices.Int32Converter;
    public static JsonConverter<long> I64 => JsonMetadataServices.Int64Converter;
    public static readonly JsonConverter<Int128> I128 = new Int128Converter();
    public static JsonConverter<byte> U8 => JsonMetadataServices.ByteConverter;
    public static JsonConverter<ushort> U16 => JsonMetadataServices.UInt16Converter;
    public static JsonConverter<uint> U32 => JsonMetadataServices.UInt32Converter;
    public static JsonConverter<ulong> U64 => JsonMetadataServices.UInt64Converter;
    public static readonly JsonConverter<UInt128> U128 = new UInt128Converter();
    public static readonly JsonConverter<float> F32 = new SingleConverter();
    public static readonly JsonConverter<double> F64 = new DoubleConverter();
    public static JsonConverter<char> Char => JsonMetadataServices.CharConverter;
    public static readonly JsonConverter<string> Str = new StringConverter();
    public static readonly JsonConverter<byte[]> Bytes = new BytesConverter();
    public static JsonConverter<Guid> Uuid => JsonMetadataServices.GuidConverter;

    /// <summary>The converter the options give <typeparamref name="T"/>: a generated type's own.</summary>
    public static JsonConverter<T> Of<T>() => TypeConverter<T>.Instance;

    public static JsonConverter<T?> Option<T>(JsonConverter<T> inner) where T : struct =>
        new OptionConverter<T>(inner);

    public static JsonConverter<T?> OptionRef<T>(JsonConverter<T> inner) where T : class =>
        new OptionRefConverter<T>(inner);

    public static JsonConverter<ObservableCollection<T>> List<T>(JsonConverter<T> element) =>
        new ListConverter<T>(element);

    public static JsonConverter<HashSet<T>> Set<T>(JsonConverter<T> element) =>
        new SetConverter<T>(element);

    public static JsonConverter<T[]> Array<T>(JsonConverter<T> element, int size) =>
        new ArrayConverter<T>(element, size);

    public static JsonConverter<Dictionary<K, V>> Map<K, V>(JsonConverter<K> key, JsonConverter<V> value)
        where K : notnull =>
        new MapConverter<K, V>(key, value);

    public static JsonConverter<(T1, T2)> Tuple<T1, T2>(JsonConverter<T1> c1, JsonConverter<T2> c2) =>
        new TupleConverter<(T1, T2)>(
            2,
            (w, v, o) => { c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 2-tuple"), Element(c2, ref r, o, "a 2-tuple")));

    public static JsonConverter<(T1, T2, T3)> Tuple<T1, T2, T3>(
        JsonConverter<T1> c1, JsonConverter<T2> c2, JsonConverter<T3> c3) =>
        new TupleConverter<(T1, T2, T3)>(
            3,
            (w, v, o) => { c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); c3.Write(w, v.Item3, o); },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 3-tuple"), Element(c2, ref r, o, "a 3-tuple"),
                 Element(c3, ref r, o, "a 3-tuple")));

    public static JsonConverter<(T1, T2, T3, T4)> Tuple<T1, T2, T3, T4>(
        JsonConverter<T1> c1, JsonConverter<T2> c2, JsonConverter<T3> c3, JsonConverter<T4> c4) =>
        new TupleConverter<(T1, T2, T3, T4)>(
            4,
            (w, v, o) =>
            {
                c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); c3.Write(w, v.Item3, o);
                c4.Write(w, v.Item4, o);
            },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 4-tuple"), Element(c2, ref r, o, "a 4-tuple"),
                 Element(c3, ref r, o, "a 4-tuple"), Element(c4, ref r, o, "a 4-tuple")));

    public static JsonConverter<(T1, T2, T3, T4, T5)> Tuple<T1, T2, T3, T4, T5>(
        JsonConverter<T1> c1, JsonConverter<T2> c2, JsonConverter<T3> c3, JsonConverter<T4> c4,
        JsonConverter<T5> c5) =>
        new TupleConverter<(T1, T2, T3, T4, T5)>(
            5,
            (w, v, o) =>
            {
                c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); c3.Write(w, v.Item3, o);
                c4.Write(w, v.Item4, o); c5.Write(w, v.Item5, o);
            },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 5-tuple"), Element(c2, ref r, o, "a 5-tuple"),
                 Element(c3, ref r, o, "a 5-tuple"), Element(c4, ref r, o, "a 5-tuple"),
                 Element(c5, ref r, o, "a 5-tuple")));

    public static JsonConverter<(T1, T2, T3, T4, T5, T6)> Tuple<T1, T2, T3, T4, T5, T6>(
        JsonConverter<T1> c1, JsonConverter<T2> c2, JsonConverter<T3> c3, JsonConverter<T4> c4,
        JsonConverter<T5> c5, JsonConverter<T6> c6) =>
        new TupleConverter<(T1, T2, T3, T4, T5, T6)>(
            6,
            (w, v, o) =>
            {
                c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); c3.Write(w, v.Item3, o);
                c4.Write(w, v.Item4, o); c5.Write(w, v.Item5, o); c6.Write(w, v.Item6, o);
            },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 6-tuple"), Element(c2, ref r, o, "a 6-tuple"),
                 Element(c3, ref r, o, "a 6-tuple"), Element(c4, ref r, o, "a 6-tuple"),
                 Element(c5, ref r, o, "a 6-tuple"), Element(c6, ref r, o, "a 6-tuple")));

    public static JsonConverter<(T1, T2, T3, T4, T5, T6, T7)> Tuple<T1, T2, T3, T4, T5, T6, T7>(
        JsonConverter<T1> c1, JsonConverter<T2> c2, JsonConverter<T3> c3, JsonConverter<T4> c4,
        JsonConverter<T5> c5, JsonConverter<T6> c6, JsonConverter<T7> c7) =>
        new TupleConverter<(T1, T2, T3, T4, T5, T6, T7)>(
            7,
            (w, v, o) =>
            {
                c1.Write(w, v.Item1, o); c2.Write(w, v.Item2, o); c3.Write(w, v.Item3, o);
                c4.Write(w, v.Item4, o); c5.Write(w, v.Item5, o); c6.Write(w, v.Item6, o);
                c7.Write(w, v.Item7, o);
            },
            (ref Utf8JsonReader r, JsonSerializerOptions o) =>
                (Element(c1, ref r, o, "a 7-tuple"), Element(c2, ref r, o, "a 7-tuple"),
                 Element(c3, ref r, o, "a 7-tuple"), Element(c4, ref r, o, "a 7-tuple"),
                 Element(c5, ref r, o, "a 7-tuple"), Element(c6, ref r, o, "a 7-tuple"),
                 Element(c7, ref r, o, "a 7-tuple")));

    // -----------------------------------------------------------------------
    // Reading and writing values
    // -----------------------------------------------------------------------

    /// <summary>The value at the reader, read with <paramref name="converter"/>.</summary>
    public static T Read<T>(JsonConverter<T> converter, ref Utf8JsonReader reader, JsonSerializerOptions options) =>
        converter.Read(ref reader, typeof(T), options)!;

    /// <summary>The map key at the reader, read with <paramref name="converter"/>.</summary>
    public static T ReadKey<T>(JsonConverter<T> converter, ref Utf8JsonReader reader, JsonSerializerOptions options) =>
        converter.ReadAsPropertyName(ref reader, typeof(T), options);

    /// <summary>Writes the field <paramref name="name"/> of an object.</summary>
    public static void WriteField<T>(
        Utf8JsonWriter writer, string name, JsonConverter<T> converter, T value, JsonSerializerOptions options)
    {
        writer.WritePropertyName(name);
        converter.Write(writer, value, options);
    }

    /// <summary>Checks that the reader is at the start of an object, the value of <paramref name="type"/>.</summary>
    public static void StartObject(ref Utf8JsonReader reader, string type)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw Expected("an object", type, ref reader);
        }
    }

    /// <summary>
    /// Moves to the next field of an object, leaving the reader at its value,
    /// or returns <c>false</c> at the end of the object.
    /// </summary>
    public static bool NextField(ref Utf8JsonReader reader, out string name)
    {
        Next(ref reader);
        if (reader.TokenType == JsonTokenType.EndObject)
        {
            name = "";
            return false;
        }
        name = reader.GetString()!;
        Next(ref reader);
        return true;
    }

    /// <summary>The value of a field that must be present.</summary>
    public static T Required<T>(bool present, T value, string field, string type) =>
        present ? value : throw new JsonException($"Missing field `{field}` of {type}");

    /// <summary>Checks that the reader is at the start of an array, the value of <paramref name="type"/>.</summary>
    public static void StartArray(ref Utf8JsonReader reader, string type)
    {
        if (reader.TokenType != JsonTokenType.StartArray)
        {
            throw Expected("an array", type, ref reader);
        }
    }

    /// <summary>The next element of an array, which must have one.</summary>
    public static T Element<T>(JsonConverter<T> converter, ref Utf8JsonReader reader, JsonSerializerOptions options, string type)
    {
        Next(ref reader);
        if (reader.TokenType == JsonTokenType.EndArray)
        {
            throw new JsonException($"Too few elements for {type}");
        }
        return converter.Read(ref reader, typeof(T), options)!;
    }

    /// <summary>Checks that the array has no more elements.</summary>
    public static void EndArray(ref Utf8JsonReader reader, string type)
    {
        Next(ref reader);
        if (reader.TokenType != JsonTokenType.EndArray)
        {
            throw new JsonException($"Too many elements for {type}");
        }
    }

    /// <summary>
    /// Reads a unit struct: <c>null</c>, or <c>{}</c>, which Rust writes for a
    /// braced struct with no fields.
    /// </summary>
    public static void ReadUnit(ref Utf8JsonReader reader, string type)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return;
        }
        StartObject(ref reader, type);
        Next(ref reader);
        if (reader.TokenType != JsonTokenType.EndObject)
        {
            throw new JsonException($"Expected null or an empty object for {type}");
        }
    }

    internal static void Next(ref Utf8JsonReader reader)
    {
        if (!reader.Read())
        {
            throw new JsonException("Unexpected end of JSON");
        }
    }

    internal static JsonException Expected(string what, string type, ref Utf8JsonReader reader) =>
        new($"Expected {what} for {type}, found {reader.TokenType}");
}

/// <summary>
/// Reads the variant of an enum and its payload, if the JSON has one, leaving
/// the reader at the payload's last token.
/// </summary>
public delegate T JsonVariantReader<T>(
    string variant, bool hasPayload, ref Utf8JsonReader reader, JsonSerializerOptions options);

/// <summary>
/// The JSON of an enum's variants, tagged as the Rust enum is: externally
/// (serde's default) with neither a tag nor content, internally with
/// <c>tag</c> alone (<c>#[serde(tag = "…")]</c>), and adjacently with both
/// (<c>#[serde(tag = "…", content = "…")]</c>).
/// </summary>
public sealed class JsonEnum(string name, string? tag = null, string? content = null)
{
    /// <summary>Writes the unit variant <paramref name="variant"/>.</summary>
    public void WriteVariant(Utf8JsonWriter writer, string variant)
    {
        if (tag is null)
        {
            writer.WriteStringValue(variant);
            return;
        }
        writer.WriteStartObject();
        writer.WriteString(tag, variant);
        writer.WriteEndObject();
    }

    /// <summary>Writes the variant <paramref name="variant"/>, holding what <paramref name="payload"/> writes.</summary>
    public void WriteVariant(Utf8JsonWriter writer, string variant, Action<Utf8JsonWriter> payload)
    {
        if (tag is null)
        {
            writer.WriteStartObject();
            writer.WritePropertyName(variant);
            payload(writer);
            writer.WriteEndObject();
            return;
        }
        if (content is not null)
        {
            writer.WriteStartObject();
            writer.WriteString(tag, variant);
            writer.WritePropertyName(content);
            payload(writer);
            writer.WriteEndObject();
            return;
        }

        // Internally tagged: the tag joins the payload's own fields.
        var buffer = new ArrayBufferWriter<byte>();
        using (var inner = new Utf8JsonWriter(buffer))
        {
            payload(inner);
        }
        using var document = JsonDocument.Parse(buffer.WrittenMemory);
        var root = document.RootElement;
        writer.WriteStartObject();
        writer.WriteString(tag, variant);
        switch (root.ValueKind)
        {
            case JsonValueKind.Object:
                foreach (var field in root.EnumerateObject())
                {
                    field.WriteTo(writer);
                }
                break;
            case JsonValueKind.Null:
                break;
            default:
                throw new JsonException(
                    $"{name}.{variant} cannot be internally tagged: its payload is not written as an object");
        }
        writer.WriteEndObject();
    }

    /// <summary>Writes the struct variant <paramref name="variant"/>, whose fields <paramref name="fields"/> writes.</summary>
    public void WriteStructVariant(Utf8JsonWriter writer, string variant, Action<Utf8JsonWriter> fields)
    {
        writer.WriteStartObject();
        if (tag is null)
        {
            writer.WritePropertyName(variant);
            writer.WriteStartObject();
            fields(writer);
            writer.WriteEndObject();
        }
        else if (content is not null)
        {
            writer.WriteString(tag, variant);
            writer.WritePropertyName(content);
            writer.WriteStartObject();
            fields(writer);
            writer.WriteEndObject();
        }
        else
        {
            writer.WriteString(tag, variant);
            fields(writer);
        }
        writer.WriteEndObject();
    }

    /// <summary>Reads a variant, calling <paramref name="read"/> with its name and payload.</summary>
    public T Read<T>(ref Utf8JsonReader reader, JsonSerializerOptions options, JsonVariantReader<T> read)
    {
        if (tag is null)
        {
            if (reader.TokenType == JsonTokenType.String)
            {
                return read(reader.GetString()!, false, ref reader, options);
            }
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw FacetJson.Expected("a variant name, or an object with a single key", name, ref reader);
            }
            FacetJson.Next(ref reader);
            if (reader.TokenType != JsonTokenType.PropertyName)
            {
                throw new JsonException($"Expected an object with a single key for {name}");
            }
            var variant = reader.GetString()!;
            FacetJson.Next(ref reader);
            var value = read(variant, true, ref reader, options);
            FacetJson.Next(ref reader);
            if (reader.TokenType != JsonTokenType.EndObject)
            {
                throw new JsonException($"Expected an object with a single key for {name}");
            }
            return value;
        }

        FacetJson.StartObject(ref reader, name);
        if (content is null)
        {
            // Internally tagged: the payload is the object without its tag.
            using var document = JsonDocument.ParseValue(ref reader);
            var root = document.RootElement;
            if (!root.TryGetProperty(tag, out var variant) || variant.ValueKind != JsonValueKind.String)
            {
                throw new JsonException($"Missing tag `{tag}` of {name}");
            }
            var buffer = new ArrayBufferWriter<byte>();
            using (var writer = new Utf8JsonWriter(buffer))
            {
                writer.WriteStartObject();
                foreach (var field in root.EnumerateObject())
                {
                    if (field.Name != tag)
                    {
                        field.WriteTo(writer);
                    }
                }
                writer.WriteEndObject();
            }
            var payload = new Utf8JsonReader(buffer.WrittenSpan);
            payload.Read();
            return read(variant.GetString()!, true, ref payload, options);
        }

        // Adjacently tagged, in either order.
        string? found = null;
        byte[]? buffered = null;
        var done = false;
        T result = default!;
        while (FacetJson.NextField(ref reader, out var key))
        {
            if (key == tag)
            {
                if (reader.TokenType != JsonTokenType.String)
                {
                    throw FacetJson.Expected("a variant name", name, ref reader);
                }
                found = reader.GetString()!;
            }
            else if (key == content)
            {
                if (found is not null)
                {
                    result = read(found, true, ref reader, options);
                    done = true;
                }
                else
                {
                    using var document = JsonDocument.ParseValue(ref reader);
                    buffered = JsonSerializer.SerializeToUtf8Bytes(document.RootElement);
                }
            }
            else
            {
                reader.Skip();
            }
        }
        if (found is null)
        {
            throw new JsonException($"Missing tag `{tag}` of {name}");
        }
        if (done)
        {
            return result;
        }
        if (buffered is not null)
        {
            var payload = new Utf8JsonReader(buffered);
            payload.Read();
            return read(found, true, ref payload, options);
        }
        return read(found, false, ref reader, options);
    }

    /// <summary>Checks the payload of a unit variant, if the JSON has one: <c>null</c>, or the fields of an object.</summary>
    public void Unit(bool hasPayload, ref Utf8JsonReader reader, string variant)
    {
        if (!hasPayload || reader.TokenType == JsonTokenType.Null)
        {
            return;
        }
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw FacetJson.Expected("null", $"{name}.{variant}", ref reader);
        }
        reader.Skip();
    }

    /// <summary>Checks that a variant that holds a value has its payload.</summary>
    public void Payload(bool hasPayload, string variant)
    {
        if (!hasPayload)
        {
            throw new JsonException($"Missing the payload of {name}.{variant}");
        }
    }

    /// <summary>A variant the enum does not have.</summary>
    public JsonException Unknown(string variant) => new($"Unknown variant `{variant}` of {name}");
}

// ---------------------------------------------------------------------------
// Converters
// ---------------------------------------------------------------------------

public static partial class FacetJson
{
    private sealed class TypeConverter<T> : JsonConverter<T>
    {
        public static readonly TypeConverter<T> Instance = new();

        public override bool HandleNull => true;

        private static JsonConverter<T> Resolve(JsonSerializerOptions options) =>
            options.GetConverter(typeof(T)) as JsonConverter<T>
                ?? throw new JsonException($"No JSON converter for {typeof(T)}");

        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            Resolve(options).Read(ref reader, typeof(T), options)!;

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) =>
            Resolve(options).Write(writer, value, options);

        public override T ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            Resolve(options).ReadAsPropertyName(ref reader, typeof(T), options);

        public override void WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options) =>
            Resolve(options).WriteAsPropertyName(writer, value!, options);
    }

    private sealed class UnitConverter : JsonConverter<Facet.Runtime.Serde.Unit>
    {
        public override Facet.Runtime.Serde.Unit Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType == JsonTokenType.Null
                ? default
                : throw FacetJson.Expected("null", "()", ref reader);

        public override void Write(Utf8JsonWriter writer, Facet.Runtime.Serde.Unit value, JsonSerializerOptions options) =>
            writer.WriteNullValue();
    }

    private sealed class BoolConverter : JsonConverter<bool>
    {
        public override bool Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.GetBoolean();

        public override void Write(Utf8JsonWriter writer, bool value, JsonSerializerOptions options) =>
            writer.WriteBooleanValue(value);

        public override bool ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.GetString() switch
            {
                "true" => true,
                "false" => false,
                var key => throw new JsonException($"Expected `true` or `false` for a bool key, found `{key}`"),
            };

        public override void WriteAsPropertyName(Utf8JsonWriter writer, bool value, JsonSerializerOptions options) =>
            writer.WritePropertyName(value ? "true" : "false");
    }

    private sealed class StringConverter : JsonConverter<string>
    {
        public override bool HandleNull => true;

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType == JsonTokenType.String
                ? reader.GetString()!
                : throw FacetJson.Expected("a string", "String", ref reader);

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options) =>
            writer.WriteStringValue(value);

        public override string ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.GetString()!;

        public override void WriteAsPropertyName(Utf8JsonWriter writer, string value, JsonSerializerOptions options) =>
            writer.WritePropertyName(value);
    }

    /// <summary>Writes a float as <c>serde_json</c> does: always with a fraction or an exponent, and <c>null</c> when it is not finite.</summary>
    private static class Floats
    {
        public static string Format(string text) =>
            text.AsSpan().IndexOfAny('.', 'E') >= 0 ? text : text + ".0";

        public static double Parse(string key) =>
            double.Parse(key, NumberStyles.Float, CultureInfo.InvariantCulture);
    }

    private sealed class DoubleConverter : JsonConverter<double>
    {
        public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.GetDouble();

        public override void Write(Utf8JsonWriter writer, double value, JsonSerializerOptions options)
        {
            if (double.IsFinite(value))
            {
                writer.WriteRawValue(Floats.Format(value.ToString("R", CultureInfo.InvariantCulture)));
            }
            else
            {
                writer.WriteNullValue();
            }
        }

        public override double ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            Floats.Parse(reader.GetString()!);

        public override void WriteAsPropertyName(Utf8JsonWriter writer, double value, JsonSerializerOptions options) =>
            writer.WritePropertyName(Floats.Format(value.ToString("R", CultureInfo.InvariantCulture)));
    }

    private sealed class SingleConverter : JsonConverter<float>
    {
        public override float Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.GetSingle();

        public override void Write(Utf8JsonWriter writer, float value, JsonSerializerOptions options)
        {
            if (float.IsFinite(value))
            {
                writer.WriteRawValue(Floats.Format(value.ToString("R", CultureInfo.InvariantCulture)));
            }
            else
            {
                writer.WriteNullValue();
            }
        }

        public override float ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            (float)Floats.Parse(reader.GetString()!);

        public override void WriteAsPropertyName(Utf8JsonWriter writer, float value, JsonSerializerOptions options) =>
            writer.WritePropertyName(Floats.Format(value.ToString("R", CultureInfo.InvariantCulture)));
    }

    /// <summary>Reads the digits of an integer too large for the reader's own accessors.</summary>
    private static class BigIntegers
    {
        public static string Digits(ref Utf8JsonReader reader, string type)
        {
            if (reader.TokenType != JsonTokenType.Number)
            {
                throw FacetJson.Expected("a number", type, ref reader);
            }
            return reader.HasValueSequence
                ? Encoding.UTF8.GetString(reader.ValueSequence.ToArray())
                : Encoding.UTF8.GetString(reader.ValueSpan);
        }
    }

    private sealed class Int128Converter : JsonConverter<Int128>
    {
        public override Int128 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            Int128.Parse(BigIntegers.Digits(ref reader, "i128"), NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture);

        public override void Write(Utf8JsonWriter writer, Int128 value, JsonSerializerOptions options) =>
            writer.WriteRawValue(value.ToString(CultureInfo.InvariantCulture));

        public override Int128 ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            Int128.Parse(reader.GetString()!, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture);

        public override void WriteAsPropertyName(Utf8JsonWriter writer, Int128 value, JsonSerializerOptions options) =>
            writer.WritePropertyName(value.ToString(CultureInfo.InvariantCulture));
    }

    private sealed class UInt128Converter : JsonConverter<UInt128>
    {
        public override UInt128 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            UInt128.Parse(BigIntegers.Digits(ref reader, "u128"), NumberStyles.None, CultureInfo.InvariantCulture);

        public override void Write(Utf8JsonWriter writer, UInt128 value, JsonSerializerOptions options) =>
            writer.WriteRawValue(value.ToString(CultureInfo.InvariantCulture));

        public override UInt128 ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            UInt128.Parse(reader.GetString()!, NumberStyles.None, CultureInfo.InvariantCulture);

        public override void WriteAsPropertyName(Utf8JsonWriter writer, UInt128 value, JsonSerializerOptions options) =>
            writer.WritePropertyName(value.ToString(CultureInfo.InvariantCulture));
    }

    /// <summary>Bytes, which Rust writes as an array of numbers from 0 to 255.</summary>
    private sealed class BytesConverter : JsonConverter<byte[]>
    {
        public override bool HandleNull => true;

        public override byte[] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            FacetJson.StartArray(ref reader, "bytes");
            var bytes = new List<byte>();
            for (FacetJson.Next(ref reader); reader.TokenType != JsonTokenType.EndArray; FacetJson.Next(ref reader))
            {
                bytes.Add(reader.GetByte());
            }
            return bytes.ToArray();
        }

        public override void Write(Utf8JsonWriter writer, byte[] value, JsonSerializerOptions options)
        {
            writer.WriteStartArray();
            foreach (var b in value)
            {
                writer.WriteNumberValue(b);
            }
            writer.WriteEndArray();
        }
    }

    private sealed class OptionConverter<T>(JsonConverter<T> inner) : JsonConverter<T?> where T : struct
    {
        public override bool HandleNull => true;

        public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType == JsonTokenType.Null ? null : inner.Read(ref reader, typeof(T), options);

        public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
        {
            if (value is { } some)
            {
                inner.Write(writer, some, options);
            }
            else
            {
                writer.WriteNullValue();
            }
        }
    }

    private sealed class OptionRefConverter<T>(JsonConverter<T> inner) : JsonConverter<T?> where T : class
    {
        public override bool HandleNull => true;

        public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType == JsonTokenType.Null ? null : inner.Read(ref reader, typeof(T), options);

        public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNullValue();
            }
            else
            {
                inner.Write(writer, value, options);
            }
        }
    }

    private abstract class SequenceConverter<C, T>(JsonConverter<T> element) : JsonConverter<C>
        where C : IEnumerable<T>
    {
        public override bool HandleNull => true;

        protected abstract C Create(List<T> items);

        public override C Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            FacetJson.StartArray(ref reader, "a sequence");
            var items = new List<T>();
            for (FacetJson.Next(ref reader); reader.TokenType != JsonTokenType.EndArray; FacetJson.Next(ref reader))
            {
                items.Add(element.Read(ref reader, typeof(T), options)!);
            }
            return Create(items);
        }

        public override void Write(Utf8JsonWriter writer, C value, JsonSerializerOptions options)
        {
            writer.WriteStartArray();
            foreach (var item in value)
            {
                element.Write(writer, item, options);
            }
            writer.WriteEndArray();
        }
    }

    private sealed class ListConverter<T>(JsonConverter<T> element)
        : SequenceConverter<ObservableCollection<T>, T>(element)
    {
        protected override ObservableCollection<T> Create(List<T> items) => new(items);
    }

    private sealed class SetConverter<T>(JsonConverter<T> element) : SequenceConverter<HashSet<T>, T>(element)
    {
        protected override HashSet<T> Create(List<T> items) => new(items);
    }

    private sealed class ArrayConverter<T>(JsonConverter<T> element, int size) : SequenceConverter<T[], T>(element)
    {
        protected override T[] Create(List<T> items) =>
            items.Count == size
                ? items.ToArray()
                : throw new JsonException($"Expected {size} elements for an array, found {items.Count}");
    }

    /// <summary>A map, which Rust writes as an object, with its keys written as strings.</summary>
    private sealed class MapConverter<K, V>(JsonConverter<K> key, JsonConverter<V> value)
        : JsonConverter<Dictionary<K, V>> where K : notnull
    {
        public override bool HandleNull => true;

        public override Dictionary<K, V> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            FacetJson.StartObject(ref reader, "a map");
            var map = new Dictionary<K, V>();
            for (FacetJson.Next(ref reader); reader.TokenType != JsonTokenType.EndObject; FacetJson.Next(ref reader))
            {
                var k = key.ReadAsPropertyName(ref reader, typeof(K), options);
                FacetJson.Next(ref reader);
                map[k] = value.Read(ref reader, typeof(V), options)!;
            }
            return map;
        }

        public override void Write(Utf8JsonWriter writer, Dictionary<K, V> map, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            foreach (var entry in map)
            {
                key.WriteAsPropertyName(writer, entry.Key, options);
                value.Write(writer, entry.Value, options);
            }
            writer.WriteEndObject();
        }
    }

    private delegate T TupleReader<T>(ref Utf8JsonReader reader, JsonSerializerOptions options);

    /// <summary>A tuple, which Rust writes as an array.</summary>
    private sealed class TupleConverter<T>(
        int size, Action<Utf8JsonWriter, T, JsonSerializerOptions> write, TupleReader<T> read) : JsonConverter<T>
    {
        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var type = $"a {size}-tuple";
            FacetJson.StartArray(ref reader, type);
            var value = read(ref reader, options);
            FacetJson.EndArray(ref reader, type);
            return value;
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            writer.WriteStartArray();
            write(writer, value, options);
            writer.WriteEndArray();
        }
    }
}
