name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci
  CI: 1
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Check (fmt + clippy)
        run: just check

      - name: Build
        run: just build

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Setup Additional Languages for codegen tests (deno)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Additional Languages for codegen tests (swift)
        uses: SwiftyLab/setup-swift@latest

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Test
        run: just test
