// JSON support for code generated by `facet_generate` with its `JsonPlugin`.
//
// The generated types are `@Serializable` and are encoded with
// kotlinx.serialization's `Json`, in the shape `serde_json` gives the same
// Rust types. A struct whose fields kotlinx already encodes the way Rust does
// uses the serializer the compiler plugin generates; every other type names
// one of the serializers below, which write the value as a `JsonElement`.

@file:OptIn(ExperimentalSerializationApi::class)

package com.novi.serde

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.SerializationStrategy
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * A serializer that writes a value as a `JsonElement` built by [toJson], and
 * reads it back with [fromJson]. It works with `Json` only.
 *
 * An enum's serializer passes its tagging: neither [tag] nor [content] for
 * serde's default external tagging, [tag] alone for `#[serde(tag = "…")]`,
 * and both for `#[serde(tag = "…", content = "…")]`.
 */
open class JsonElementSerializer<T>(
    private val name: String,
    private val tag: String? = null,
    private val content: String? = null,
    private val toJson: JsonWriter.(T) -> JsonElement,
    private val fromJson: JsonReader.(JsonElement) -> T,
) : KSerializer<T> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor(name)

    override fun serialize(encoder: Encoder, value: T) {
        val jsonEncoder = encoder as? JsonEncoder
            ?: throw SerializationException("$name can only be serialized to JSON")
        val writer = JsonWriter(jsonEncoder.json, name, tag, content)
        jsonEncoder.encodeJsonElement(writer.toJson(value))
    }

    override fun deserialize(decoder: Decoder): T {
        val jsonDecoder = decoder as? JsonDecoder
            ?: throw SerializationException("$name can only be deserialized from JSON")
        val reader = JsonReader(jsonDecoder.json, name, tag, content)
        return reader.fromJson(jsonDecoder.decodeJsonElement())
    }
}

/**
 * A serializer for a newtype struct, which Rust writes as the value it wraps.
 *
 * It delegates to [serializer], so it works with any format, and a newtype
 * of a string or a number can be a map key.
 */
open class JsonNewTypeSerializer<T, V>(
    private val serializer: () -> KSerializer<V>,
    private val wrap: (V) -> T,
    private val unwrap: (T) -> V,
) : KSerializer<T> {
    override val descriptor: SerialDescriptor get() = serializer().descriptor

    override fun serialize(encoder: Encoder, value: T) =
        encoder.encodeSerializableValue(serializer(), unwrap(value))

    override fun deserialize(decoder: Decoder): T =
        wrap(decoder.decodeSerializableValue(serializer()))
}

/** Builds the JSON for a value of the type [name]. */
class JsonWriter internal constructor(
    val json: Json,
    private val name: String,
    private val tag: String?,
    private val content: String?,
) {
    /** [value], encoded with [serializer]. */
    fun <V> encode(serializer: SerializationStrategy<V>, value: V): JsonElement =
        json.encodeToJsonElement(serializer, value)

    /** A JSON array: a tuple struct's fields, or a tuple variant's. */
    fun array(vararg elements: JsonElement): JsonElement = JsonArray(elements.toList())

    /** A JSON object: a struct's fields, or a struct variant's. */
    fun obj(vararg fields: Pair<String, JsonElement>): JsonElement = JsonObject(mapOf(*fields))

    /** `null`, which Rust writes for a unit struct. */
    fun unit(): JsonElement = JsonNull

    /** The unit variant [variant], tagged as the enum is. */
    fun variant(variant: String): JsonElement = when {
        tag == null -> JsonPrimitive(variant)
        else -> JsonObject(mapOf(tag to JsonPrimitive(variant)))
    }

    /** The variant [variant] holding [payload], tagged as the enum is. */
    fun variant(variant: String, payload: JsonElement): JsonElement = when {
        tag == null -> JsonObject(mapOf(variant to payload))
        content != null -> JsonObject(mapOf(tag to JsonPrimitive(variant), content to payload))
        // Internally tagged: the tag joins the payload's own fields.
        payload is JsonObject -> JsonObject(mapOf(tag to JsonPrimitive(variant)) + payload)
        payload is JsonNull -> JsonObject(mapOf(tag to JsonPrimitive(variant)))
        else -> throw SerializationException(
            "$name.$variant cannot be internally tagged: its payload is not written as an object"
        )
    }
}

/** A variant's name, and its payload if the JSON has one. */
data class JsonVariant(val name: String, val payload: JsonElement?)

/** The fields of a JSON object, looked up by name. */
class JsonFields internal constructor(
    private val name: String,
    private val fields: JsonObject,
) {
    /** The field [key], which must be present. */
    fun required(key: String): JsonElement =
        fields[key] ?: throw SerializationException("Missing field `$key` of $name")

    /** The field [key], or `null` when it is missing, as Rust reads an `Option`. */
    fun optional(key: String): JsonElement = fields[key] ?: JsonNull
}

/** Reads the JSON of a value of the type [name]. */
class JsonReader internal constructor(
    val json: Json,
    private val name: String,
    private val tag: String?,
    private val content: String?,
) {
    /** The value [element] holds, decoded with [serializer]. */
    fun <V> decode(serializer: DeserializationStrategy<V>, element: JsonElement): V =
        json.decodeFromJsonElement(serializer, element)

    /** The [size] elements of the array [element]. */
    fun tuple(element: JsonElement?, size: Int): List<JsonElement> {
        val array = element as? JsonArray ?: throw expected("an array", element)
        if (array.size != size) {
            throw SerializationException("Expected $size elements for $name, found ${array.size}")
        }
        return array
    }

    /** The fields of the object [element]. */
    fun fields(element: JsonElement?): JsonFields =
        JsonFields(name, element as? JsonObject ?: throw expected("an object", element))

    /** Checks that [element] is a unit struct: `null`, or `{}` for a struct with no fields. */
    fun unit(element: JsonElement) {
        if (element !is JsonNull && !(element is JsonObject && element.isEmpty())) {
            throw expected("null", element)
        }
    }

    /** The variant [element] holds, tagged as the enum is. */
    fun variant(element: JsonElement): JsonVariant {
        if (tag == null) {
            if (element is JsonPrimitive && element.isString) {
                return JsonVariant(element.content, null)
            }
            val obj = element as? JsonObject
            if (obj == null || obj.size != 1) {
                throw expected("a variant name, or an object with a single key", element)
            }
            val (variant, payload) = obj.entries.single()
            return JsonVariant(variant, payload)
        }
        val obj = element as? JsonObject ?: throw expected("an object", element)
        val variant = obj[tag] as? JsonPrimitive
        if (variant == null || !variant.isString) {
            throw SerializationException("Missing tag `$tag` of $name")
        }
        return when (content) {
            null -> JsonVariant(variant.content, JsonObject(obj - tag))
            else -> JsonVariant(variant.content, obj[content])
        }
    }

    /** The payload of a variant, which must have one. */
    fun payload(payload: JsonElement?): JsonElement =
        payload ?: throw SerializationException("Missing the payload of a variant of $name")

    /** Fails on a variant [variant] the enum does not have. */
    fun unknownVariant(variant: String): Nothing =
        throw SerializationException("Unknown variant `$variant` of $name")

    private fun expected(what: String, element: JsonElement?) =
        SerializationException("Expected $what for $name, found $element")
}

/** Rust's `()`, which JSON writes as `null`. */
object JsonUnitSerializer : KSerializer<Unit> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("kotlin.Unit")

    override fun serialize(encoder: Encoder, value: Unit) {
        val jsonEncoder = encoder as? JsonEncoder
            ?: throw SerializationException("() can only be serialized to JSON")
        jsonEncoder.encodeJsonElement(JsonNull)
    }

    override fun deserialize(decoder: Decoder) {
        val jsonDecoder = decoder as? JsonDecoder
            ?: throw SerializationException("() can only be deserialized from JSON")
        val element = jsonDecoder.decodeJsonElement()
        if (element !is JsonNull) {
            throw SerializationException("Expected null for (), found $element")
        }
    }
}

/** A Rust 2-tuple, which JSON writes as an array. */
class JsonPairSerializer<A, B>(
    private val first: KSerializer<A>,
    private val second: KSerializer<B>,
) : JsonElementSerializer<Pair<A, B>>(
    "a 2-tuple",
    toJson = { value -> array(encode(first, value.first), encode(second, value.second)) },
    fromJson = { element ->
        val items = tuple(element, 2)
        Pair(decode(first, items[0]), decode(second, items[1]))
    },
)

/** A Rust 3-tuple, which JSON writes as an array. */
class JsonTripleSerializer<A, B, C>(
    private val first: KSerializer<A>,
    private val second: KSerializer<B>,
    private val third: KSerializer<C>,
) : JsonElementSerializer<Triple<A, B, C>>(
    "a 3-tuple",
    toJson = { value ->
        array(encode(first, value.first), encode(second, value.second), encode(third, value.third))
    },
    fromJson = { element ->
        val items = tuple(element, 3)
        Triple(decode(first, items[0]), decode(second, items[1]), decode(third, items[2]))
    },
)
